# Generated by Django 3.2.13 on 2022-04-27 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transformationledger',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termset',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='mapping',
            field=models.ManyToManyField(blank=True, related_name='_core_term_mapping_+', to='core.Term'),
        ),
        migrations.AddField(
            model_name='term',
            name='term_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.termset'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemaledger',
            name='term_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='core.termset'),
        ),
        migrations.AddField(
            model_name='schemaledger',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='schemaledger',
            constraint=models.UniqueConstraint(fields=('schema_name', 'version'), name='unique_schema'),
        ),
        migrations.AddField(
            model_name='childtermset',
            name='parent_term_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.termset'),
        ),
    ]
