# Generated by Django 3.2.13 on 2022-05-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220509_2037'),
        ('core', '0002_auto_20220518_1531'),
    ]

    operations = [
    ]
